return {
  'folke/trouble.nvim',
  opts = {},
  cmd = "Trouble",
  dependencies = 'nvim-tree/nvim-web-devicons',
  keys = {
    { "<leader>x",  group = "Trouble" },
    { "<leader>xx", "<cmd>Trouble diagnostics toggle<cr>",                        desc = "Toggle" },
    { "<leader>xd", "<cmd>Trouble diagnostics toggle filter.buf=0<cr>",           desc = "Document Diagnostics" },
    { "<leader>xw", "<cmd>Trouble diagnostics toggle<cr>",                        desc = "Workspace Diagnostics" },
    { "<leader>xs", "<cmd>Trouble symbols toggle focus=false<cr>",                desc = "Symbols (Trouble)" },
    { "<leader>xr", "<cmd>Trouble lsp toggle focus=false win.position=right<cr>", desc = "LSP Definitions / references" },
    { "<leader>xq", "<cmd>Trouble qflist toggle<cr>",                             desc = "Quickfix List" },
    { "<leader>xL", "<cmd>Trouble loclist toggle<cr>",                            desc = "Location List" },
    { "<leader>xj", vim.diagnostic.goto_next,                                     desc = "Next" },
    { "<leader>xk", vim.diagnostic.goto_prev,                                     desc = "Previous" },
    { "<leader>xh", vim.cmd.cprev,                                                desc = "Previous in Quickfix" },
    { "<leader>xl", vim.cmd.cnext,                                                desc = "Next in Quickfix" },
  },
}
