require('guerra.vim')
require('guerra.formatting')
require('guerra.linting')
require('guerra.lsp')
require('guerra.treesitter')
require('guerra.chat-gpt')
require('guerra.remap')
-- require('guerra.rest')
require('guerra.aerial')
require('guerra.ufo')
require('guerra.trouble')
require('guerra.easypick')
-- require('guerra.sg')
require('guerra.nvim-tree')
require('guerra.copilot')
require('guerra.debugger')
