require('user.vim')
require('user.formatting')
require('user.linting')
require('user.lsp')
require('user.treesitter')
require('user.remap')
-- require('user.rest')
require('user.aerial')
require('user.ufo')
require('user.trouble')
require('user.easypick')
-- require('user.sg')
require('user.nvim-tree')
